// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_GUI

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SubmitLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_SubmitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SubmitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SubmitLabel, -4 );
lv_obj_set_y( ui_SubmitLabel, 0 );
lv_obj_set_align( ui_SubmitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SubmitLabel,"Submit to Bosse pressing both buttons");
lv_obj_set_style_text_color(ui_SubmitLabel, lv_color_hex(0xBFBFBF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SubmitLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SubmitLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnterEmailField = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_EnterEmailField, 300);
lv_obj_set_height( ui_EnterEmailField, 50);
lv_obj_set_x( ui_EnterEmailField, 0 );
lv_obj_set_y( ui_EnterEmailField, -45 );
lv_obj_set_align( ui_EnterEmailField, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_EnterEmailField,"Enter Email Address (Push Button)");


lv_obj_set_style_text_color(ui_EnterEmailField, lv_color_hex(0xBFBFBF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_EnterEmailField, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_EnterPasswordField = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_EnterPasswordField, 300);
lv_obj_set_height( ui_EnterPasswordField, 50);
lv_obj_set_x( ui_EnterPasswordField, 0 );
lv_obj_set_y( ui_EnterPasswordField, 45 );
lv_obj_set_align( ui_EnterPasswordField, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_EnterPasswordField,"Enter Password (Push Button)");


lv_obj_set_style_text_color(ui_EnterPasswordField, lv_color_hex(0xBFBFBF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_EnterPasswordField, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

}
