// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_GUI

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BosseImage = lv_img_create(ui_Screen1);
lv_img_set_src(ui_BosseImage, &ui_img_favicon_png);
lv_obj_set_width( ui_BosseImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BosseImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BosseImage, 131 );
lv_obj_set_y( ui_BosseImage, -1 );
lv_obj_set_align( ui_BosseImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BosseImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BosseImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_BosseImage,10);

ui_SubmitLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_SubmitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SubmitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SubmitLabel, -39 );
lv_obj_set_y( ui_SubmitLabel, 0 );
lv_obj_set_align( ui_SubmitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SubmitLabel,"Push both buttons to Submit");

ui_EnterEmailField = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_EnterEmailField, 300);
lv_obj_set_height( ui_EnterEmailField, 50);
lv_obj_set_x( ui_EnterEmailField, 0 );
lv_obj_set_y( ui_EnterEmailField, -45 );
lv_obj_set_align( ui_EnterEmailField, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_EnterEmailField,"Enter Email Address (Push Button)");



ui_EnterPasswordField = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_EnterPasswordField, 300);
lv_obj_set_height( ui_EnterPasswordField, 50);
lv_obj_set_x( ui_EnterPasswordField, 0 );
lv_obj_set_y( ui_EnterPasswordField, 45 );
lv_obj_set_align( ui_EnterPasswordField, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_EnterPasswordField,"Enter Password (Push Button)");



}
