// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_GUI

#ifndef _SQUARELINE_GUI_UI_H
#define _SQUARELINE_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_BosseImage;
extern lv_obj_t *ui_SubmitLabel;
extern lv_obj_t *ui_EnterEmailField;
extern lv_obj_t *ui_EnterPasswordField;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_favicon_png);   // assets/favicon.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
